### ISSUE TITLE
Change "Let's verify if you are a Nad" to something else

### ISSUE THREAD

**Issue by portdeveloper** [monad-devrel/monad-discord-auth#12]
![image](https://github.com/user-attachments/assets/99e00d8e-4097-41b0-816f-7385875f73f9)

Currently we are asking the person visiting the app if they are a Nad.

But we don't check if that person is a "Nad", we check for at least full access and if the user has nads role.

I think we should change the wording here to something better.

**Comment by portdeveloper** [comment]
> Hi @portdeveloper So i am a beginner and i guess i have some wordings to put on instead of a nad , so can you please assign this to me. It could also help me in building my open source journey

Yes!! Please do take your time on this!

**Comment by Rahul-2006** [comment]
I made a pull request 
If you want any changes let me know
